MOVW    0X03    ; MAKE EIGHT INPUTS
MOVWR   TRISA   ; PORTB MAKE INPUTS

CLEAR:        ;CLEARS THE DISPLAY,THEN SETS TO 0
   
CALL COUNT0
MOVW 0X00
MOVWR 0XDF

START:
MOVRW  PORTA
ANDW   0X01
JPZ    CHECK_BUTTON_PRESS
MOVRW  PORTA
ANDW   0X02
JPZ    CHECK_BUTTON_PRESS
JMP    START

CHECK_BUTTON_PRESS:
MOVRW PORTA
ORW 0X03
JPZ CHECK_BUTTON_PRESS


DOUBLE_CHECK:
MOVRW PORTA
XORW  0X00
JPZ START

BUTTON_IS_PRESSED:
INC  0XDE


UP:            ;CHECKS IF IT NEEDS TO COUNT UP
    MOVRW  PORTA   
    ANDW   0X02      ; WHEN B2 PRESSED
    JPZ    DOWN	 ; IF 0, READ AGAIN
    JMP    ADD_ONE   ; IF 1, THEN ADD 1 TO W

ADD_ONE:  
INC  0XDF
    JMP READ
    
DOWN:  ;CHECKS IF IT NEEDS TO COUNT DOWN
    MOVRW PORTA
    ANDW  0X01
    JPZ   START
   
CHECK_0:
MOVRW  0XDF
ORW    0X00
JPZ    START

SUB_ONE:
DEC 0XDF
    JMP READ
    
; ====== ALARM =======
READER: 
    MOVRW  	PORTA    	; MOVE PORTA TO W
    ANDW   0X06  ; CHECK IF NUM = 6 
    JPZ      READ       ; GO BACK TO NUM POLLING
    JMP    	ALARM  	       ; IF 6, THEN JUMP ALARM

ALARM:
    MOVW 	0x9   	; spin2win
    MOVWR   PORTC        ; MOVE TO PORTC
    CALL   	ALARMTIME 	; TIME DELAY SUBROUTINE

ALARMOFF:
    MOVW	0X03   	; CLOSE BIT0 AND BIT3 
    MOVWR 	PORTC	    ; SEND TO PORTC
    JMP    CLEAR      ; START READING AGAIN
		
; ===== ALARMON TIME =======
ALARMTIME:
    MOVW     0x30   		; 10 SEC

REP1:
    SUBW     0x1   		; MINUS 1
    JPZ      FIN    		; I.E. TURN OFF
    JMP      REP1  		; KEEP -1'ING 

FIN:
    JMP      ALARMOFF

; ====== LEWIS CODE =======
; ==== 0 TO 6 COUNTER =====

READ:         ;TRANSLATES THE WORKING REGISTER 
              ;INTO THE 7 SEG DISPLAY
NOP
CON_READ:

CALL STORED ;EXTRACTS FROM THE MEMORY LOCATION
SUBW 0X01
JPZ  COUNT1

CALL STORED
SUBW 0X02
JPZ  COUNT2

CALL STORED
SUBW 0X03
JPZ  COUNT3

CALL STORED
SUBW 0X04
JPZ  COUNT4

CALL STORED
SUBW 0X05
JPZ  COUNT5

CALL STORED
SUBW 0X06
JPZ  COUNT6

;===============================================
COUNT0:    
    MOVW    0X7D
    MOVWR   PORTB
   CALL STOP_COUNT
RET

COUNT1:
    MOVW    0X05    ; CONTROL DATA TO W (ONE)
    MOVWR   PORTB   ; COPY DATA TO PORT
    CALL STOP_COUNT
JMP START  
 
COUNT2:         
    MOVW    0X5B    ; CONTROL DATA TO W (TWO)
    MOVWR   PORTB   ; COPY DATA TO PORT
    CALL STOP_COUNT
JMP START 

COUNT3:
    MOVW    0X4F
    MOVWR   PORTB
    CALL STOP_COUNT
JMP START 

COUNT4:
    MOVW    0X27
    MOVWR   PORTB
    CALL STOP_COUNT
JMP START 

COUNT5:
    MOVW    0X6E
    MOVWR   PORTB
    CALL STOP_COUNT
JMP START 

COUNT6:
    MOVW    0X7E
    MOVWR   PORTB
    CALL STOP_COUNT
JMP READER 

STORED:
MOVRW  0XDF
RET

STOP_COUNT:
     DEC     0XDE
     MOVRW   0XDE
     JPZ     START
LET_IT_GO:
     MOVRW   PORTA
     ORW     0X00
     JPZ     SWITCHED
     JMP     LET_IT_GO
SWITCHED:     
RET
